name: build brain

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: install pnpm
        run: npm install -g pnpm
      
      - name: install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
      
      - name: install frontend dependencies
        run: pnpm install
      
      - name: generate icons
        run: pnpm generate-icons
      
      - name: build
        run: pnpm build-app
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: brain-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/
            src-tauri/target/release/brain
            src-tauri/target/release/brain.exe